[package]
authors = ["Daniel Stahl <danstahl1138@gmail.com>"]
description = "A Black Scholes option pricing library."
edition = "2018"
homepage = "https://github.com/danielhstahl/black_scholes_rust"
license = "MIT"
name = "black_scholes"
readme = "README.md"
repository = "https://github.com/danielhstahl/black_scholes_rust"
version = "0.6.1"

[dependencies]
nrfind = "1.0.2"
statrs = "^0.13.0"

[dev-dependencies]
approx = "0.2.0"
rand = "0.5"

[profile.bench]
lto = true

[badges]
travis-ci = {repository = "danielhstahl/black_scholes_rust"}
